import type { LeadershipMember } from "@/config/leadership";

export type PastPresident = LeadershipMember & {
  rotaryYear: string;
  yearStart: number;
};

/**
 * College of Presidents / Hall of Fame — RSAMDIO Presidents by Rotary Year.
 * Formal portraits live in /public/img/presidents/ as WebP.
 */
export const pastPresidents: PastPresident[] = [
  {
    name: "Karthik Kittu",
    title: "Rotary Year 2010–11",
    rotaryYear: "2010–11",
    yearStart: 2010,
    district: "District 3191",
    country: "India",
    image: "/img/presidents/karthik-kittu.webp",
  },
  {
    name: "Thansen Paandi",
    title: "Rotary Year 2011–12",
    rotaryYear: "2011–12",
    yearStart: 2011,
    district: "District 3150",
    country: "India",
    image: "/img/presidents/thansen-paandi.webp",
  },
  {
    name: "Harikrishnan Pillai",
    title: "Rotary Year 2012–13",
    rotaryYear: "2012–13",
    yearStart: 2012,
    district: "District 3141",
    country: "India",
    image: "/img/presidents/harikrishnan-pillai.webp",
  },
  {
    name: "Suresh Manoharan",
    title: "Rotary Year 2013–14",
    rotaryYear: "2013–14",
    yearStart: 2013,
    district: "District 3232",
    country: "India",
    image: "/img/presidents/suresh-manoharan.webp",
  },
  {
    name: "Amit Singhal",
    title: "Rotary Year 2014–15",
    rotaryYear: "2014–15",
    yearStart: 2014,
    district: "District 3080",
    country: "India",
    image: "/img/presidents/amit-singhal.webp",
  },
  {
    name: "Tapas Kumar Das",
    title: "Rotary Year 2015–16",
    rotaryYear: "2015–16",
    yearStart: 2015,
    district: "District 3262",
    country: "India",
    image: "/img/presidents/tapas-kumar-das.webp",
  },
  {
    name: "Rajesh Subramanian",
    title: "Rotary Year 2016–17",
    rotaryYear: "2016–17",
    yearStart: 2016,
    district: "District 3150",
    country: "India",
    image: "/img/presidents/rajesh-subramanian.webp",
  },
  {
    name: "Jimry Henry",
    title: "Rotary Year 2017–18",
    rotaryYear: "2017–18",
    yearStart: 2017,
    district: "District 3206",
    country: "India",
    image: "/img/presidents/jimry-henry.webp",
  },
  {
    name: "Shashwat Desai",
    title: "Rotary Year 2018–19",
    rotaryYear: "2018–19",
    yearStart: 2018,
    district: "District 3054",
    country: "India",
    image: "/img/presidents/shashwat-desai.webp",
  },
  {
    name: "Manuj Mittal",
    title: "Rotary Year 2019–20",
    rotaryYear: "2019–20",
    yearStart: 2019,
    district: "District 3011",
    country: "India",
    image: "/img/presidents/manuj-mittal.webp",
  },
  {
    name: "Yatin Sehgal",
    title: "Rotary Year 2020–21",
    rotaryYear: "2020–21",
    yearStart: 2020,
    district: "District 3090",
    country: "India",
    image: "/img/presidents/yatin-sehgal.webp",
  },
  {
    name: "Arti J Goswami",
    title: "Rotary Year 2021–22",
    rotaryYear: "2021–22",
    yearStart: 2021,
    district: "District 3030",
    country: "India",
    image: "/img/presidents/arti-j-goswami.webp",
  },
  {
    name: "Zia Uddin Haider",
    title: "Rotary Year 2022–23",
    rotaryYear: "2022–23",
    yearStart: 2022,
    district: "District 3282",
    country: "Bangladesh",
    image: "/img/presidents/zia-uddin-haider.webp",
  },
  {
    name: "Girish Easwaran",
    title: "Rotary Year 2023–24",
    rotaryYear: "2023–24",
    yearStart: 2023,
    district: "District 3233",
    country: "India",
    image: "/img/presidents/girish-easwaran.webp",
  },
  {
    name: "Sahil Pradeep Gandhi",
    title: "Rotary Year 2024–25",
    rotaryYear: "2024–25",
    yearStart: 2024,
    district: "District 3170",
    country: "India",
    image: "/img/presidents/sahil-pradeep-gandhi.webp",
  },
  {
    name: "Darryl Steven Dsouza",
    title: "Rotary Year 2025–26",
    rotaryYear: "2025–26",
    yearStart: 2025,
    district: "District 3181",
    country: "India",
    image: "/img/presidents/darryl-steven-dsouza.webp",
  },
  {
    name: "Arun Teja Godavarthi",
    title: "Rotary Year 2026–27",
    rotaryYear: "2026–27",
    yearStart: 2026,
    district: "District 3191",
    country: "India",
    image: "/img/presidents/arun-teja-godavarthi.webp",
  },
  {
    name: "Kiran S H S",
    title: "Rotary Year 2027–28",
    rotaryYear: "2027–28",
    yearStart: 2027,
    district: "District 3192",
    country: "India",
    image: "/img/presidents/kiran-s-h-s.webp",
  },
];

