// Leadership directory — Official RSAMDIO Executive Board, Committee, and DRRs Roster.

export type LeadershipMember = {
  name: string;
  title: string;
  district: string;
  country: string;
  image?: string;
  role?: string;
  email?: string;
  homeClub?: string;
  profession?: string;
  group?: string;
  committee?: string;
};

export const executiveBoard: LeadershipMember[] = [
  // --- CORE EXECUTIVE OFFICERS ---
  {
    name: "Arun Teja Godavarthi",
    title: "President",
    district: "District 3191",
    country: "India",
    image: "/img/board/arun-teja-godavarthi.webp",
    role: "president",
    email: "president2627rsamdio@gmail.com",
    homeClub: "Rotaract Club of Bangalore East",
    profession: "Business & Ecosystem Leader, Reliance Intelligence",
  },
  {
    name: "Kiran S H S",
    title: "President Elect",
    district: "District 3192",
    country: "India",
    image: "/img/board/kiran-s-h-s.webp",
    role: "officer",
    email: "rtrkiranshs@gmail.com",
    homeClub: "Rotaract Club of Bangalore Golden Rock",
    profession: "Advocate",
  },
  {
    name: "Darryl Steven Dsouza",
    title: "Immediate Past President",
    district: "District 3181",
    country: "India",
    image: "/img/board/darryl-steven-dsouza.webp",
    role: "officer",
    email: "Darryl.dsouza14@gmail.com",
    homeClub: "Rotaract Club of Mangalore City",
    profession: "Logistics Business / Mechanical Engineer",
  },
  {
    name: "Harikrishnan Pillai",
    title: "Chief Counsellor",
    district: "District 3141",
    country: "India",
    image: "/img/board/harikrishnan-pillai.webp",
    role: "officer",
    email: "hari@tsbi.in",
    homeClub: "Rotaract Club of District 3141",
    profession: "Executive Leadership",
  },
  {
    name: "Joseph Wilson",
    title: "Vice President",
    district: "District 3192",
    country: "India",
    image: "/img/board/joseph-wilson.webp",
    role: "officer",
    email: "joewilson.3993@gmail.com",
    homeClub: "Rotaract Club of Bangalore",
    profession: "IT Professional",
  },
  {
    name: "Sasikumar Janakiraman",
    title: "General Secretary",
    district: "District 3234",
    country: "India",
    image: "/img/board/sasikumar-janakiraman.webp",
    role: "secretary",
    email: "3234drr@gmail.com",
    homeClub: "Rotaract Club of Chennai",
    profession: "Creative Director",
  },
  {
    name: "Kriti Malhotra",
    title: "Secretary, Reporting and Communications",
    district: "District 3011",
    country: "India",
    image: "/img/board/kriti-malhotra.webp",
    role: "secretary",
    email: "rtrkritimalhotra@gmail.com",
    homeClub: "Rotaract Club of Delhi Janak",
    profession: "Program Associate - Simple Education Foundation",
  },
  {
    name: "Sathish Kumar S",
    title: "Secretary, Programs and Initiatives",
    district: "District 3234",
    country: "India",
    image: "/img/board/sathish-kumar-s.webp",
    role: "secretary",
    email: "sathishkbc@gmail.com",
    homeClub: "Rotaract Club of Ambattur",
    profession: "Graphic Designer",
  },
  {
    name: "Jitesh Bhatia",
    title: "Joint Secretary",
    district: "District 3142",
    country: "India",
    image: "/img/board/jitesh-bhatia.webp",
    role: "secretary",
    email: "rtrjiteshbhatia@gmail.com",
    homeClub: "Rotaract Club of Ulhasnagar Sapna Garden",
    profession: "Lead Software Engineer",
  },
  {
    name: "Shanmugavel",
    title: "Treasurer",
    district: "District 3000",
    country: "India",
    image: "/img/board/shanmugavel.webp",
    role: "treasurer",
    email: "shanmugavels17@gmail.com",
    homeClub: "Rotaract Club of Madurai North",
    profession: "Finance (Tax consultant & Mutual fund distributor)",
  },
  {
    name: "Nishan Ahmmed",
    title: "Sergeant at Arms",
    district: "District 3204",
    country: "India",
    image: "/img/board/nishan-ahmmed.webp",
    role: "officer",
    email: "nishan.ahammed@gmail.com",
    homeClub: "Rotaract Club of Calicut Central",
    profession: "Fabrication Contractor",
  },

  // --- SPECIALIZED CHAIRS & EDITORS ---
  {
    name: "Aniket Satish Jadhav",
    title: "Chair, Awards & Recognitions",
    district: "District 3170",
    country: "India",
    image: "/img/board/aniket-satish-jadhav.webp",
    role: "chair",
    email: "drraniket3170@gmail.com",
    homeClub: "Rotaract Club of Venugram - Belgaum",
    profession: "Businessman",
  },
  {
    name: "Thanghapantieyaan A K",
    title: "Chair, Membership & Service Programs",
    district: "District 3206",
    country: "India",
    image: "/img/board/thanghapantieyaan-a-k.webp",
    role: "chair",
    email: "rtrtp3201@gmail.com",
    homeClub: "Rotaract Club of Coimbatore Texcity",
    profession: "Specialist - HR & Talent Acquisition",
  },
  {
    name: "Gowtham S",
    title: "Editor",
    district: "District 2982",
    country: "India",
    image: "/img/board/gowtham-s.webp",
    role: "editor",
    email: "rtrgowthams@gmail.com",
    homeClub: "Rotaract Club of Salem Gems",
    profession: "IT Employee",
  },
  {
    name: "Aloka Dey",
    title: "Editor",
    district: "District 3240",
    country: "India",
    image: "/img/board/aloka-dey.webp",
    role: "editor",
    email: "alokadey33@gmail.com",
    homeClub: "Rotaract Club of Naharkatia",
    profession: "Teacher",
  },

  // --- DIRECTORS BY GROUP & PORTFOLIO ---
  {
    name: "Rohit Ashish Ajmera",
    title: "Director, Zone 4",
    district: "District 3060",
    country: "India",
    image: "/img/board/rohit-ashish-ajmera.webp",
    role: "director",
    group: "Zone 4",
    email: "drrrohit3060@gmail.com",
    homeClub: "Rotaract Club of Dhule Cross Road",
    profession: "Businessman",
  },
  {
    name: "Kaavya Jain",
    title: "Director, Zone 4",
    district: "District 3012",
    country: "India",
    image: "/img/board/kaavya-jain.webp",
    role: "director",
    group: "Zone 4",
    email: "kaavyajain1807@gmail.com",
    homeClub: "Rotaract Club of Sonepat",
    profession: "Advocate",
  },
  {
    name: "Gamith Shanel Mendis",
    title: "Director, Zone 5",
    district: "District 3220",
    country: "Sri Lanka",
    image: "/img/board/gamith-shanel-mendis.webp",
    role: "director",
    group: "Zone 5",
    email: "mendisshanel@gmail.com",
    homeClub: "Rotaract Club of Panadura",
    profession: "Lead - DevOps Engineering",
  },
  {
    name: "Sathish Balakrishnan",
    title: "Director, Zone 5",
    district: "District 3206",
    country: "India",
    image: "/img/board/sathish-balakrishnan.webp",
    role: "director",
    group: "Zone 5",
    email: "rtrsathish3201@gmail.com",
    homeClub: "Rotaract Club of CUG (Covai User Group)",
    profession: "RSA Leadership",
  },
  {
    name: "Ashish Nikam",
    title: "Director, Zone 6",
    district: "District 3030",
    country: "India",
    image: "/img/board/ashish-nikam.webp",
    role: "director",
    group: "Zone 6",
    email: "ashishnikam3030@gmail.com",
    homeClub: "Rotaract Club of Nasik Grape Valley",
    profession: "Businessman",
  },
  {
    name: "Roshan Karki",
    title: "Director, Zone 6",
    district: "District 3292",
    country: "Nepal",
    image: "/img/board/roshan-karki.webp",
    role: "director",
    group: "Zone 6",
    email: "roshankarki15@gmail.com",
    homeClub: "Rotaract Club of Manohara",
    profession: "Tourism & Remittance Industry",
  },
  {
    name: "Harsh Paresh Shinde",
    title: "Director, Zone 7",
    district: "District 3170",
    country: "India",
    image: "/img/board/harsh-paresh-shinde.webp",
    role: "director",
    group: "Zone 7",
    email: "drrharsh3170@gmail.com",
    homeClub: "Rotaract Club of Venugram - Belgaum",
    profession: "Architect / Anchor",
  },
  {
    name: "Yashwardhan Chauhan",
    title: "Director, International Relations",
    district: "District 3141",
    country: "India",
    image: "/img/board/yashwardhan-chauhan.webp",
    role: "director",
    email: "drryashwardhanchauhan@gmail.com",
    homeClub: "Rotaract Club of Borivali Heights",
    profession: "Account Manager",
  },
  {
    name: "Janice Philip",
    title: "Director, International Relations",
    district: "District 3192",
    country: "India",
    image: "/img/board/janice-philip.webp",
    role: "director",
    email: "janicephilip903@gmail.com",
    homeClub: "Rotaract Club of Vidyaranyapura",
    profession: "SAP Consultant",
  },
  {
    name: "Prajwal R",
    title: "Director, Service Programs",
    district: "District 3181",
    country: "India",
    image: "/img/board/prajwal-r.webp",
    role: "director",
    email: "rtrprajwal@gmail.com",
    homeClub: "Rotaract Club of Mysore",
    profession: "Founder - Sri Shankara Financial Services",
  },
  {
    name: "Nikhita Sunil",
    title: "Director, Membership Programs",
    district: "District 3141",
    country: "India",
    image: "/img/board/nikhita-sunil.webp",
    role: "director",
    email: "drrnikhitasunil@gmail.com",
    homeClub: "Rotaract Club of Borivali Heights",
    profession: "Lawyer and Entrepreneur",
  },
  {
    name: "S Shreevarshan",
    title: "Director, Foundation Programs",
    district: "District 3203",
    country: "India",
    image: "/img/board/s-shreevarshan.webp",
    role: "director",
    email: "rtrshreevarshan3202@gmail.com",
    homeClub: "Rotaract Club of Pollachi Varnas",
    profession: "Political Consultant",
  },
  {
    name: "Ajai S",
    title: "Director, Learning Programs",
    district: "District 3206",
    country: "India",
    image: "/img/board/ajai-s.webp",
    role: "director",
    email: "mailxajai@gmail.com",
    homeClub: "Rotaract Club of CUG (Covai User Group)",
    profession: "IT Professional",
  },
  {
    name: "Vaibhav Thakur",
    title: "Director, Learning Programs",
    district: "District 3250",
    country: "India",
    image: "/img/board/vaibhav-thakur.webp",
    role: "director",
    email: "rtr.vaibhav3250@gmail.com",
    homeClub: "Rotaract Club of Muzaffarpur",
    profession: "Professional & Community Leader",
  },
  {
    name: "Ruchit Mehta",
    title: "Director, Fellowship Programs",
    district: "District 3060",
    country: "India",
    image: "/img/board/ruchit-mehta.webp",
    role: "director",
    email: "ruchitrotaract@gmail.com",
    homeClub: "Rotaract Club of Bharuch Next",
    profession: "Multimedia Post Production Services",
  },
  {
    name: "Gopalakrishanan P",
    title: "Director, Fellowship Programs",
    district: "District 3000",
    country: "India",
    image: "/img/board/gopalakrishanan-p.webp",
    role: "director",
    email: "gopalgops026@gmail.com",
    homeClub: "Rotaract Club of Aranthangi",
    profession: "Entrepreneur",
  },
  {
    name: "Nazmi Mahamood",
    title: "Director, Marketing & Communications",
    district: "District 3220",
    country: "Sri Lanka",
    image: "/img/board/nazmi-mahamood.webp",
    role: "director",
    email: "nazmi.rotaract3220@gmail.com",
    homeClub: "Rotaract Club of Colombo Fort",
    profession: "Brand Marketing",
  },
  {
    name: "Nikhil Ramesh Chindak",
    title: "Director, Partnerships & CSR Programs",
    district: "District 3170",
    country: "India",
    image: "/img/board/nikhil-ramesh-chindak.webp",
    role: "director",
    email: "rtrnikhilchindak@gmail.com",
    homeClub: "Rotaract Club of Belgaum South",
    profession: "Businessman",
  },
  {
    name: "Siddhesh Gaikwad",
    title: "Director, Partnerships & CSR Programs",
    district: "District 3131",
    country: "India",
    image: "/img/board/siddhesh-gaikwad.webp",
    role: "director",
    email: "drrsiddheshgaikwad3131@gmail.com",
    homeClub: "Rotaract Club of Pune Kalyani Nagar",
    profession: "Businessman",
  },
  {
    name: "Nivas M R",
    title: "Director, Vocational Programs",
    district: "District 3182",
    country: "India",
    image: "/img/board/nivas-m-r.webp",
    role: "director",
    email: "drrnivas.rid3182@gmail.com",
    homeClub: "Rotaract Club of Shimoga North Elite",
    profession: "Assistant Manager - Business Operations",
  },
  {
    name: "Sailesh Proddaturu",
    title: "Director, Vocational Programs",
    district: "District 3150",
    country: "India",
    image: "/img/board/sailesh-proddaturu.webp",
    role: "director",
    email: "rtrsaileshp@gmail.com",
    homeClub: "Rotaract Club of Hyderabad East",
    profession: "Businessman",
  },
  {
    name: "Surya Kiran K",
    title: "Director, Reach RSA",
    district: "District 3192",
    country: "India",
    image: "/img/board/surya-kiran-k.webp",
    role: "director",
    email: "rtr.suryakiran@gmail.com",
    homeClub: "Rotaract Club of Bangalore West",
    profession: "Entrepreneur",
  },
  {
    name: "T Selvavignesh Periyanayaki",
    title: "Director, Reach RSA",
    district: "District 3203",
    country: "India",
    image: "/img/board/t-selvavignesh-periyanayaki.webp",
    role: "director",
    email: "rtr.vicky07@gmail.com",
    homeClub: "Rotaract Club of Adaiyalam",
    profession: "Entrepreneur",
  },

  // --- HOST DRRs & SPECIAL REPRESENTATIVES ---
  {
    name: "Vijay Vignesh V K",
    title: "RZI Host DRR",
    district: "District 3206",
    country: "India",
    image: "/img/board/vijay-vignesh-v-k.webp",
    role: "host",
    email: "vijayvigneshk7@gmail.com",
    homeClub: "Rotaract Club of Coimbatore Gaalaxy",
    profession: "Software Test Engineer",
  },
  {
    name: "Yashovardhan Kothari",
    title: "Rotasia Host DRR",
    district: "District 3040",
    country: "India",
    image: "/img/board/yashovardhan-kothari.webp",
    role: "host",
    email: "drryashovardhankothari3040@gmail.com",
    homeClub: "Rotaract E-Club of Club of Indore Royals (E-Club)",
    profession: "Director & CEO",
  },
  {
    name: "Anirudh G Kulkarni",
    title: "President Home District DRR",
    district: "District 3191",
    country: "India",
    image: "/img/board/anirudh-g-kulkarni.webp",
    role: "host",
    email: "drr2627rotaract3191@gmail.com",
    homeClub: "Rotaract Club of Bengaluru JP Nagar",
    profession: "Psephologist",
  },
];

// District Rotaract Representatives — Full Official Roster RY 2026–27
// Zones aligned to RI Zone sheet (District → RI Zone)
export const drrs: LeadershipMember[] = [
  // Zone 4
  { name: "Archit Bhatia", title: "DRR, District 3011", district: "District 3011", country: "India", image: "/img/drr/archit-bhatia.webp", homeClub: "Rotaract Club of Delhi Heights", group: "Zone 4" },
  { name: "Harshita Dhakad", title: "DRR, District 3012", district: "District 3012", country: "India", image: "/img/drr/harshita-dhakad.webp", homeClub: "Rotaract Club of O.P.Jindal Global University", group: "Zone 4" },
  { name: "Khushi Chauhan", title: "DRR, District 3053", district: "District 3053", country: "India", image: "/img/drr/khushi-chauhan.webp", homeClub: "Rotaract Club of Gwalior Heritage", group: "Zone 4" },
  { name: "Aneri Nilesh Bhatt", title: "DRR, District 3055", district: "District 3055", country: "India", image: "/img/drr/aneri-bhatt.webp", homeClub: "Rotaract Club of Ahmedabad Elysium", group: "Zone 4" },
  { name: "Aishwarya Singh", title: "DRR, District 3056", district: "District 3056", country: "India", image: "/img/drr/aishwarya-singh.webp", homeClub: "Rotaract Club of Aishwarya", group: "Zone 4" },
  { name: "Rohan Tuli", title: "DRR, District 3070", district: "District 3070", country: "India", image: "/img/drr/rohan-tuli.webp", homeClub: "Rotaract Club of Ludhiana North", group: "Zone 4" },
  { name: "Kashish Narula", title: "DRR, District 3090", district: "District 3090", country: "India", image: "/img/drr/kashish-narula.webp", homeClub: "Rotaract Club of Nabha Greater", group: "Zone 4" },

  // Zone 5
  { name: "M Manikandan", title: "DRR, District 2982", district: "District 2982", country: "India", image: "/img/drr/manikandan-m.webp", homeClub: "Rotaract Club of Salem", group: "Zone 5" },
  { name: "Harish Amudavel", title: "DRR, District 3000", district: "District 3000", country: "India", image: "/img/drr/harish-amudavel.webp", homeClub: "Rotaract Club of Boiler City Trichy", group: "Zone 5" },
  { name: "Varun Kumar", title: "DRR, District 3203", district: "District 3203", country: "India", image: "/img/drr/varun-kumar.webp", homeClub: "Rotaract Club of Udumalpet Yuvas", group: "Zone 5" },
  { name: "Vijay Vignesh V K", title: "DRR, District 3206", district: "District 3206", country: "India", image: "/img/drr/vijay-vignesh-v-k.webp", homeClub: "Rotaract Club of Coimbatore Gaalaxy", group: "Zone 5" },
  { name: "Vigneshwaran Prabakaran", title: "DRR, District 3212", district: "District 3212", country: "India", image: "/img/drr/vigneshwaran-prabakaran.webp", homeClub: "Rotaract Club of virudhunagar", group: "Zone 5" },
  { name: "Jude Shannon Lucian", title: "DRR, District 3220", district: "District 3220", country: "Sri Lanka", image: "/img/drr/jude-lucian.webp", homeClub: "Rotaract Club of Kandy Metropolitan", group: "Zone 5" },
  { name: "Harivignesh M", title: "DRR, District 3233", district: "District 3233", country: "India", image: "/img/drr/harivignesh-m.webp", homeClub: "Rotaract Club of Green Galaxy", group: "Zone 5" },
  { name: "Vignesh Chandran", title: "DRR, District 3234", district: "District 3234", country: "India", image: "/img/drr/vignesh-chandran.webp", homeClub: "Rotaract Club of Coastal Legacy", group: "Zone 5" },

  // Zone 6
  { name: "Garima Singh", title: "DRR, District 3120", district: "District 3120", country: "India", image: "/img/drr/garima-singh.webp", homeClub: "Rotaract Club of Prayagraj Sangam City", group: "Zone 6" },
  { name: "Pintu Sharma", title: "DRR, District 3240", district: "District 3240", country: "India", image: "/img/drr/pintu-sharma.webp", homeClub: "Rotaract Club of Gangtok Hills", group: "Zone 6" },
  { name: "Sadashiv Khatri", title: "DRR, District 3250", district: "District 3250", country: "India", image: "/img/drr/sadashiv-khatri.webp", homeClub: "Rotaract Club of Chaibasa", group: "Zone 6" },
  { name: "Preeti prangya panda", title: "DRR, District 3261", district: "District 3261", country: "India", image: "/img/drr/preeti-prangya-panda.webp", homeClub: "Rotary Club of Rourkela Steel City", group: "Zone 6" },
  { name: "Mukesh Kumar Samal", title: "DRR, District 3262", district: "District 3262", country: "India", image: "/img/drr/mukesh-kumar.webp", homeClub: "Rotaract Club of Bhubaneswar Royal", group: "Zone 6" },
  { name: "Prakash Gaire (Sharma)", title: "DRR, District 3292", district: "District 3292", country: "Nepal", image: "/img/drr/prakash-sharma.webp", homeClub: "Rotaract Club of Bhairahawa", group: "Zone 6" },

  // Zone 7
  { name: "Prabhu Kalyan Ratnala", title: "DRR, District 3020", district: "District 3020", country: "India", image: "/img/drr/prabhu-kalyan-ratnala.webp", homeClub: "Rotaract Club of Royal City Bezawada", group: "Zone 7" },
  { name: "Sudheeshna Muthyapu", title: "DRR, District 3150", district: "District 3150", country: "India", image: "/img/drr/sudheeshna.webp", homeClub: "Rotaract Club of Sunrise", group: "Zone 7" },
  { name: "Managala Purushotham", title: "DRR, District 3160", district: "District 3160", country: "India", image: "/img/drr/managala-purushotham.webp", homeClub: "Rotaract Club of Srit", group: "Zone 7" },
  { name: "Amey Mangesh Varerkar", title: "DRR, District 3170", district: "District 3170", country: "India", image: "/img/drr/amey-varerkar.webp", homeClub: "Rotaract Club of Mapusa", group: "Zone 7" },
  { name: "Shree Raksha P P", title: "DRR, District 3181", district: "District 3181", country: "India", image: "/img/drr/shree-raksha.webp", homeClub: "Rotaract Club of Mysore East", group: "Zone 7" },
  { name: "Reshma Ramesh", title: "DRR, District 3182", district: "District 3182", country: "India", image: "/img/drr/reshma-r.webp", homeClub: "Rotaract Club of Manipal Central", group: "Zone 7" },
  { name: "Anirudh G Kulkarni", title: "DRR, District 3191", district: "District 3191", country: "India", image: "/img/drr/anirudh-kulkarni.webp", homeClub: "Rotaract Club of Bangalore JP Nagar", group: "Zone 7" },
  { name: "Sanjay R", title: "DRR, District 3192", district: "District 3192", country: "India", image: "/img/drr/sanjay-r.webp", homeClub: "Rotaract Club of Bangalore Udyog", group: "Zone 7" },
  { name: "Sooraj Babu Parambath", title: "DRR, District 3204", district: "District 3204", country: "India", image: "/img/drr/sooraj-babu.webp", homeClub: "Rotaract Club of Calicut East", group: "Zone 7" },
  { name: "Namith Krishna", title: "DRR, District 3205", district: "District 3205", country: "India", image: "/img/drr/namith-krishna.webp", homeClub: "Rotaract Club of Cochin East", group: "Zone 7" },
  { name: "Muhammed Sha S L", title: "DRR, District 3211", district: "District 3211", country: "India", image: "/img/drr/muhammed-sha.webp", homeClub: "Rotaract Club of Trivandrum Suburban NSSA", group: "Zone 7" },

  // Zone 8
  { name: "Yogesh Ashok Jadhav", title: "DRR, District 3030", district: "District 3030", country: "India", image: "/img/drr/yogesh-jadhav.webp", homeClub: "Rotaract Club of Satana Pride", group: "Zone 8" },
  { name: "Yashovardhan Kothari", title: "DRR, District 3040", district: "District 3040", country: "India", image: "/img/drr/yashovardhan-kothari.webp", homeClub: "Rotaract E-Club of Indore Royals", group: "Zone 8" },
  { name: "Bhavya Samirkumar Shah", title: "DRR, District 3060", district: "District 3060", country: "India", image: "/img/drr/bhavya-shah.webp", homeClub: "Rotaract Club of Navsari Young Turks", group: "Zone 8" },
  { name: "Karishma Awari", title: "DRR, District 3131", district: "District 3131", country: "India", image: "/img/drr/karishma-awari.webp", homeClub: "Rotaract Club of Pune Shaniwarwada", group: "Zone 8" },
  { name: "Amit Pravin Bhosale", title: "DRR, District 3132", district: "District 3132", country: "India", image: "/img/drr/amit-bhosale.webp", homeClub: "Rotaract Club of Karad City", group: "Zone 8" },
  { name: "Shreehari Nair", title: "DRR, District 3141", district: "District 3141", country: "India", image: "/img/drr/shree-nair.webp", homeClub: "Rotaract Club of Bombay Pier", group: "Zone 8" },
  { name: "Himanshu R Dapurkar", title: "DRR, District 3142", district: "District 3142", country: "India", image: "/img/drr/himanshu-dapurkar.webp", homeClub: "Rotaract Club of Thane Downtown", group: "Zone 8" },
].sort((a, b) => {
  const num = (district: string) => {
    const match = district.match(/\d+/);
    return match ? Number(match[0]) : Number.POSITIVE_INFINITY;
  };
  return num(a.district) - num(b.district);
});

export const committeeMembers: LeadershipMember[] = [
  {
    name: "Tanya Vasista",
    title: "Committee Member",
    committee: "Design and Visual Communications",
    district: "District 3182",
    country: "India",
    image: "/img/committee/tanya-vasista.webp",
    homeClub: "Rotaract Club of Shimoga North Elite",
    profession: "Design engineer"
  },
  {
    name: "Navin Bharathi Pandiarajan",
    title: "Committee Member",
    committee: "Design and Visual Communications",
    district: "District 3203",
    country: "India",
    image: "/img/committee/navin-bharathi-pandiarajan.webp",
    homeClub: "Rotaract Club of Erode Kalam",
    profession: "Structural Engineer"
  },
  {
    name: "Lokhamitra Boopathi",
    title: "Committee Member",
    committee: "Design and Visual Communications",
    district: "District 3203",
    country: "India",
    image: "/img/committee/lokhamitra-boopathi.webp",
    homeClub: "Rotaract Club of Velalar College of Engineering & Technology",
    profession: "PG Student"
  },
  {
    name: "Akanksha Anil Tiwari",
    title: "Committee Member",
    committee: "Design and Visual Communications",
    district: "District 3132",
    country: "India",
    image: "/img/committee/akanksha-anil-tiwari.webp",
    homeClub: "Rotaract Club of Karad City",
    profession: "Freelance Graphic Designer"
  },
  {
    name: "Sanjay Siva",
    title: "Committee Member",
    committee: "Design and Visual Communications",
    district: "District 3234",
    country: "India",
    image: "/img/committee/sanjay-siva.webp",
    homeClub: "Rotaract Club of Ambattur",
    profession: "Graphic Designer"
  },
  {
    name: "Taha Muliwala",
    title: "Committee Member",
    committee: "Editorial and Content",
    district: "District 3141",
    country: "India",
    image: "/img/committee/taha-muliwala.webp",
    homeClub: "Rotaract Club of Bombay Mid-Town",
    profession: "Analyst Fund Administration @ Russell Investments"
  },
  {
    name: "Gnaana Abirami",
    title: "Committee Member",
    committee: "Editorial and Content",
    district: "District 3234",
    country: "India",
    image: "/img/committee/gnaana-abirami.webp",
    homeClub: "Rotaract Club of Madras",
    profession: "Psychologist"
  },
  {
    name: "Nida Fatima A Bhavnagary",
    title: "Committee Member",
    committee: "Editorial and Content",
    district: "District 3181",
    country: "India",
    image: "/img/committee/nida-fatima-a-bhavnagary.webp",
    homeClub: "Rotaract Club of Mysore",
    profession: "Indian Sign Language Interpreter, Social Entrepreneur, Voice-over Artist"
  },
  {
    name: "Hitaishi Chawla",
    title: "Committee Member",
    committee: "Editorial and Content",
    district: "District 3011",
    country: "India",
    image: "/img/committee/hitaishi-chawla.webp",
    homeClub: "Rotaract Club of Delhi Genesis",
    profession: "Student"
  },
  {
    name: "Nakul Kaswani",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3060",
    country: "India",
    image: "/img/committee/nakul-kaswani.webp",
    homeClub: "Rotaract Club of Vadodara",
    profession: "Post Graduate"
  },
  {
    name: "Chinmay S Muragi",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3170",
    country: "India",
    image: "/img/committee/chinmay-s-muragi.webp",
    homeClub: "Rotaract Club of Twin City",
    profession: "HR"
  },
  {
    name: "Esha Jain",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3170",
    country: "India",
    image: "/img/committee/esha-jain.webp",
    homeClub: "Rotaract Club of Venugram-Belgaum",
    profession: "Regulatory Affairs Specialist"
  },
  {
    name: "Vansh Saini",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3011",
    country: "India",
    image: "/img/committee/vansh-saini.webp",
    homeClub: "Rotaract Club of Delhi Genesis Midwest",
    profession: "AI Trainer & Consultant | Podcast Host"
  },
  {
    name: "Jaiakash S",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3206",
    country: "India",
    image: "/img/committee/jaiakash-s.webp",
    homeClub: "Rotaract Club of TNAU(TAMILNADU Agricultural University )",
    profession: "Student and Agri business"
  },
  {
    name: "Raunak Agrawal",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3141",
    country: "India",
    image: "/img/committee/raunak-agrawal.webp",
    homeClub: "Rotaract Club of IHM Mumbai",
    profession: "Student & Self Employed"
  },
  {
    name: "Shubham Oza",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3030",
    country: "India",
    image: "/img/committee/shubham-oza.webp",
    homeClub: "Rotaract Club of Nashik Airport",
    profession: "HR Professional"
  },
  {
    name: "Apurva Ravi",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3206",
    country: "India",
    image: "/img/committee/apurva-ravi.webp",
    homeClub: "Rotaract Club of Coimbatore Main",
    profession: "MBA Student"
  },
  {
    name: "Harshad Laxmikant Joshi",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3170",
    country: "India",
    image: "/img/committee/harshad-laxmikant-joshi.webp",
    homeClub: "Rotaract Club of Venugram - Belgaum",
    profession: "Data Analyst"
  },
  {
    name: "Harshit Deepak Kulkarni",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3170",
    country: "India",
    image: "/img/committee/harshit-deepak-kulkarni.webp",
    homeClub: "Rotaract Club of Venugram - Belgaum",
    profession: "Data Scientist"
  },
  {
    name: "Malcolm Vakharia",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3141",
    country: "India",
    image: "/img/committee/malcolm-vakharia.webp",
    homeClub: "Rotaract Club of Bombay Mid-Town",
    profession: "Business Development Manager & Part time Professor"
  },
  {
    name: "Akshay Kumar B S",
    title: "Committee Member",
    committee: "Programs & Operations",
    district: "District 3191",
    country: "India",
    image: "/img/committee/akshay-kumar-b-s.webp",
    homeClub: "Rotaract Club of Bangalore SouthWest",
    profession: "Business"
  },
  {
    name: "Praneeth Madusanka",
    title: "Committee Member",
    committee: "Social Media and Outreach",
    district: "District 3220",
    country: "India",
    image: "/img/committee/praneeth-madusanka.webp",
    homeClub: "Rotaract Club of Colombo Port City",
    profession: "Marketeer"
  },
  {
    name: "Mahi Azad",
    title: "Committee Member",
    committee: "Social Media and Outreach",
    district: "District 3011",
    country: "India",
    image: "/img/committee/mahi-azad.webp",
    homeClub: "Rotaract Club of Delhi Genesis",
    profession: "M.Com Student at Shri Ram College of Commerce, Delhi University"
  },
  {
    name: "Aashna",
    title: "Committee Member",
    committee: "Social Media and Outreach",
    district: "District 3142",
    country: "India",
    image: "/img/committee/aashna.webp",
    homeClub: "Rotaract Club of DYPSBB Satellite City",
    profession: "Student"
  },
  {
    name: "Dharanidharan A",
    title: "Committee Member",
    committee: "Video & Story Telling",
    district: "District 3234",
    country: "India",
    image: "/img/committee/dharanidharan-a.webp",
    homeClub: "Rotaract Club of Madras Central",
    profession: "Motion graphic designer"
  },
  {
    name: "Sainath Tupdol",
    title: "Committee Member",
    committee: "Video & Story Telling",
    district: "District 3142",
    country: "India",
    image: "/img/committee/sainath-tupdol.webp",
    homeClub: "Rotaract Club of kalyan heritage city",
    profession: "Graduation completed"
  },
  {
    name: "Sasmitha Danidu Silva",
    title: "Committee Member",
    committee: "Web and Tech",
    district: "District 3220",
    country: "India",
    image: "/img/committee/sasmitha-danidu-silva.webp",
    homeClub: "Rotaract Club of University of Colombo School of Computing",
    profession: "Quality Engineer"
  },
  {
    name: "Deepan P",
    title: "Committee Member",
    committee: "Web and Tech",
    district: "District 3206",
    country: "India",
    image: "/img/committee/deepan-p.webp",
    homeClub: "Rotaract Club of Coimbatore City",
    profession: "Full Stack Developer"
  },
  {
    name: "Samarth Viswanath",
    title: "Committee Member",
    committee: "Web and Tech",
    district: "District 3191",
    country: "India",
    image: "/img/committee/samarth-viswanath.webp",
    homeClub: "Rotaract Club of Bangalore JP Nagar",
    profession: "Lead Software Engineer"
  },
  {
    name: "Kiran",
    title: "Committee Member",
    committee: "Web and Tech",
    district: "District 3181",
    country: "India",
    image: "/img/committee/kiran.webp",
    homeClub: "Rotaract Club of Mit Fgc",
    profession: "Intern at Vtech solutions (STU-DEV)"
  }
].sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" }));

export type PastLeadershipYear = {
  year: string;
  president: string;
  country: string;
};

// Most recent terms first.
export const pastLeadership: PastLeadershipYear[] = [
  { year: "2025–26", president: "Devan Wickramasinghe", country: "Sri Lanka" },
  { year: "2024–25", president: "Simran Kaur", country: "India" },
  { year: "2023–24", president: "Faisal Rahman", country: "Bangladesh" },
];
